# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=11, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('api_key', models.CharField(blank=True, max_length=32, null=True)),
                ('fcm_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.CharField(max_length=100)),
                ('aadhar', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='DestinationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.CharField(blank=True, db_column='seats', max_length=100, null=True)),
                ('seats_available', models.IntegerField(db_column='seats_available')),
                ('cost', models.CharField(blank=True, db_column='cost', max_length=10, null=True)),
                ('dateofride', models.CharField(blank=True, db_column='dateofride', max_length=20, null=True)),
                ('start_time', models.CharField(blank=True, db_column='start_time', max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('ridecancelstatus', models.IntegerField(db_column='rideCancelStatus')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='SourceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rides')),
            ],
        ),
        migrations.CreateModel(
            name='UserRides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'user_rides',
            },
        ),
        migrations.AddField(
            model_name='destinationlocation',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rides'),
        ),
    ]
