# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('rate', models.FloatField(db_column='rate')),
                ('fb_id', models.CharField(db_column='fb_id', max_length=100)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
