# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171221_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='dateofride',
            field=models.CharField(blank=True, db_column='dateofride', max_length=20, null=True),
        ),
    ]
