# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171221_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
