# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171221_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationlocation',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='sourcelocation',
            name='ride',
        ),
        migrations.AddField(
            model_name='rides',
            name='destination',
            field=models.CharField(blank=True, db_column='destination', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='destination_latitude',
            field=models.CharField(blank=True, db_column='destination_latitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='destination_longitude',
            field=models.CharField(blank=True, db_column='destination_longitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='source',
            field=models.CharField(blank=True, db_column='source', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='source_latitude',
            field=models.CharField(blank=True, db_column='source_latitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='source_longitude',
            field=models.CharField(blank=True, db_column='source_longitude', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DestinationLocation',
        ),
        migrations.DeleteModel(
            name='SourceLocation',
        ),
    ]
